/**
 * additivePurchases data export
 * Generated: 2025-09-29T19:38:24.548Z
 *
 * IMPORTANT: You can manually edit this file to adjust for schema changes.
 * - Add/remove fields as needed
 * - Update field names to match new schema
 * - Modify values
 *
 * When importing, the import script will validate against current schema.
 */

export const additivePurchasesData = [
  {
    id: "e3202669-ddf3-4b50-aef6-a5531781406b",
    vendorId: "88030c4f-658c-4411-b7c2-804970eefd57",
    purchaseDate: "2025-09-24T00:00:00.000Z",
    totalCost: "60.00",
    invoiceNumber: "2025-09-24-88030c4f-658c-4411-b7c2-804970eefd57-001-ADD",
    autoGeneratedInvoice: true,
    notes: "Cane Sugar purchased from vendor",
    createdAt: "2025-09-24T14:12:25.897Z",
    updatedAt: "2025-09-24T14:12:25.897Z",
    deletedAt: null
  },
  {
    id: "5ca9e1be-9903-4d07-aa76-7f50f0b4adb2",
    vendorId: "88030c4f-658c-4411-b7c2-804970eefd57",
    purchaseDate: "2025-09-24T00:00:00.000Z",
    totalCost: "60.00",
    invoiceNumber: "2025-09-24-88030c4f-658c-4411-b7c2-804970eefd57-001-ADD",
    autoGeneratedInvoice: true,
    notes: "Additives purchased from Costco",
    createdAt: "2025-09-24T19:04:39.321Z",
    updatedAt: "2025-09-24T19:04:39.321Z",
    deletedAt: null
  },
  {
    id: "7d7faadd-8e36-4e96-93c5-3348e99c1cd4",
    vendorId: "88030c4f-658c-4411-b7c2-804970eefd57",
    purchaseDate: "2025-09-24T00:00:00.000Z",
    totalCost: "60.00",
    invoiceNumber: "2025-09-24-88030c4f-658c-4411-b7c2-804970eefd57-001-ADD",
    autoGeneratedInvoice: true,
    notes: "Additives purchased from Costco",
    createdAt: "2025-09-24T19:20:04.912Z",
    updatedAt: "2025-09-24T19:20:04.912Z",
    deletedAt: null
  }
] as const;

export default additivePurchasesData;
