/**
 * juicePurchases data export
 * Generated: 2025-09-29T19:38:24.186Z
 *
 * IMPORTANT: You can manually edit this file to adjust for schema changes.
 * - Add/remove fields as needed
 * - Update field names to match new schema
 * - Modify values
 *
 * When importing, the import script will validate against current schema.
 */

export const juicePurchasesData = [
  {
    id: "31e0538d-23cb-4104-8d38-9f5a8e0c274d",
    vendorId: "fda97909-3ebb-4125-b4e7-9727876ca34f",
    purchaseDate: "2025-09-24T00:00:00.000Z",
    totalCost: "50.00",
    invoiceNumber: "2025-09-24-fda97909-3ebb-4125-b4e7-9727876ca34f-001-JUI",
    autoGeneratedInvoice: true,
    notes: "Apple Juice purchased from vendor",
    createdAt: "2025-09-24T16:21:41.046Z",
    updatedAt: "2025-09-24T16:21:41.046Z",
    deletedAt: null
  },
  {
    id: "334e7608-b76d-4238-8421-d6a441e4675f",
    vendorId: "fda97909-3ebb-4125-b4e7-9727876ca34f",
    purchaseDate: "2025-09-24T00:00:00.000Z",
    totalCost: "99.90",
    invoiceNumber: "2025-09-24-fda97909-3ebb-4125-b4e7-9727876ca34f-001-JUI",
    autoGeneratedInvoice: true,
    notes: "Juice purchased from FruitSmart",
    createdAt: "2025-09-24T19:23:55.951Z",
    updatedAt: "2025-09-24T19:23:55.951Z",
    deletedAt: null
  },
  {
    id: "747930c9-e158-4764-b0c6-fab28183b349",
    vendorId: "fda97909-3ebb-4125-b4e7-9727876ca34f",
    purchaseDate: "2025-09-26T00:00:00.000Z",
    totalCost: "0.00",
    invoiceNumber: "2025-09-26-fda97909-3ebb-4125-b4e7-9727876ca34f-001-JUI",
    autoGeneratedInvoice: true,
    notes: "Juice purchased from FruitSmart",
    createdAt: "2025-09-26T17:24:57.593Z",
    updatedAt: "2025-09-26T17:24:57.593Z",
    deletedAt: null
  },
  {
    id: "e29d1a10-0252-47c3-a1be-05e790c4d021",
    vendorId: "fda97909-3ebb-4125-b4e7-9727876ca34f",
    purchaseDate: "2025-09-27T00:00:00.000Z",
    totalCost: "0.00",
    invoiceNumber: "2025-09-27-fda97909-3ebb-4125-b4e7-9727876ca34f-001-JUI",
    autoGeneratedInvoice: true,
    notes: "Juice purchased from FruitSmart",
    createdAt: "2025-09-27T15:49:19.764Z",
    updatedAt: "2025-09-27T15:49:19.764Z",
    deletedAt: null
  },
  {
    id: "4f6ca8b3-0a37-46e9-9315-0de2550d260d",
    vendorId: "fda97909-3ebb-4125-b4e7-9727876ca34f",
    purchaseDate: "2025-09-27T00:00:00.000Z",
    totalCost: "0.00",
    invoiceNumber: "2025-09-27-fda97909-3ebb-4125-b4e7-9727876ca34f-001-JUI",
    autoGeneratedInvoice: true,
    notes: "Juice purchased from FruitSmart",
    createdAt: "2025-09-27T16:09:52.513Z",
    updatedAt: "2025-09-27T16:09:52.513Z",
    deletedAt: null
  },
  {
    id: "2ffaca65-d6bf-4ac9-ade2-fee225ef351c",
    vendorId: "fda97909-3ebb-4125-b4e7-9727876ca34f",
    purchaseDate: "2025-09-27T00:00:00.000Z",
    totalCost: "0.00",
    invoiceNumber: "2025-09-27-fda97909-3ebb-4125-b4e7-9727876ca34f-001-JUI",
    autoGeneratedInvoice: true,
    notes: "Juice purchased from FruitSmart",
    createdAt: "2025-09-27T16:15:56.727Z",
    updatedAt: "2025-09-27T16:15:56.727Z",
    deletedAt: null
  },
  {
    id: "ac9c6673-33e4-423a-9de6-0d4a160ec0b6",
    vendorId: "fda97909-3ebb-4125-b4e7-9727876ca34f",
    purchaseDate: "2025-09-27T00:00:00.000Z",
    totalCost: "0.00",
    invoiceNumber: "2025-09-27-fda97909-3ebb-4125-b4e7-9727876ca34f-001-JUI",
    autoGeneratedInvoice: true,
    notes: "Juice purchased from FruitSmart",
    createdAt: "2025-09-27T16:22:17.996Z",
    updatedAt: "2025-09-27T16:22:17.996Z",
    deletedAt: null
  }
] as const;

export default juicePurchasesData;
